// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TsuD_j4hJCo4z4x4xALA3_mQPJQ8Z4Y',
    appId: '1:381999526651:web:2ad399481eb6993124765e',
    messagingSenderId: '381999526651',
    projectId: 'to-do-list-d56ac',
    authDomain: 'to-do-list-d56ac.firebaseapp.com',
    storageBucket: 'to-do-list-d56ac.appspot.com',
    measurementId: 'G-28GT2858YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAix4hZf__jbnKIu8bKLOAOUGT7ZB-M7KQ',
    appId: '1:381999526651:android:94dd88b19626a2ff24765e',
    messagingSenderId: '381999526651',
    projectId: 'to-do-list-d56ac',
    storageBucket: 'to-do-list-d56ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltM_U1iodPsyRifC45sdA7r48zDJdZ-s',
    appId: '1:381999526651:ios:7e595712dd8d573b24765e',
    messagingSenderId: '381999526651',
    projectId: 'to-do-list-d56ac',
    storageBucket: 'to-do-list-d56ac.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
